# Generated by Django 3.2 on 2022-03-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(blank=True, choices=[('collect', 'collect'), ('contact', 'contact')], default='collect', max_length=200, null=True, verbose_name='type')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='email')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='name')),
                ('helpType', models.CharField(blank=True, choices=[('Buying NFTs', 'Buying NFTs'), ('Question about NFT art', 'Question about NFT art'), ('Participating in an NFT project', 'Participating in an NFT project'), ('Question about K-NFT', 'Question about K-NFT'), ('Partnering with K-NFT', 'Partnering with K-NFT'), ('Other', 'Other')], default='Buying NFTs', max_length=200, null=True, verbose_name='helpType')),
                ('message', models.CharField(blank=True, max_length=200, null=True, verbose_name='message')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
            },
        ),
    ]
