# Generated by Django 3.2 on 2022-03-13 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, null=True, unique=True, verbose_name='작가명')),
                ('authDes', models.CharField(max_length=50, null=True, verbose_name='작가설명')),
                ('desTitle', models.CharField(max_length=50, null=True, verbose_name='작가 타이틀')),
                ('description', models.TextField(blank=True, null=True, verbose_name='작가 컨텐츠')),
                ('discord', models.CharField(blank=True, max_length=50, null=True, verbose_name='discord')),
                ('facebook', models.CharField(blank=True, max_length=50, null=True, verbose_name='facebook')),
                ('instargram', models.CharField(blank=True, max_length=50, null=True, verbose_name='instargram')),
                ('twitter', models.CharField(blank=True, max_length=50, null=True, verbose_name='twitter')),
                ('show', models.BooleanField(default=True, verbose_name='노출')),
                ('avator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='files.file')),
            ],
            options={
                'verbose_name': '작가',
                'verbose_name_plural': '작가모음',
                'ordering': ['name'],
            },
        ),
    ]
