# Generated by Django 3.2 on 2022-03-13 11:21

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(blank=True, max_length=80, null=True, verbose_name='작가이름')),
                ('caption', models.CharField(blank=True, max_length=80, null=True, verbose_name='사진이름')),
                ('file', models.FileField(upload_to=files.models.File.get_file_path)),
                ('content_type', models.CharField(blank=True, editable=False, max_length=128, null=True)),
                ('thumnail', models.FileField(blank=True, null=True, upload_to='')),
                ('file360', models.FileField(blank=True, null=True, upload_to='')),
                ('file800', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': '파일',
                'verbose_name_plural': '파일모음',
            },
        ),
    ]
