# Generated by Django 3.2 on 2022-03-18 04:35

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_file_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file360',
            field=models.FileField(blank=True, null=True, upload_to=files.models.File.get_detail_file_path),
        ),
        migrations.AlterField(
            model_name='file',
            name='file800',
            field=models.FileField(blank=True, null=True, upload_to=files.models.File.get_detail_file_path),
        ),
        migrations.AlterField(
            model_name='file',
            name='thumnail',
            field=models.FileField(blank=True, null=True, upload_to=files.models.File.get_detail_file_path),
        ),
    ]
