# Generated by Django 3.2 on 2022-03-18 04:56

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20220318_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=files.models.File.get_file_path),
        ),
    ]
