# Generated by Django 3.2 on 2022-03-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220318_0618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='projectType',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('project', 'project'), ('edition', 'edition'), ('other', 'other')], default='project', max_length=40, null=True, verbose_name='product_type'),
        ),
    ]
