# Generated by Django 3.2 on 2022-03-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20220318_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='foundataionLink',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='foundataionLink'),
        ),
        migrations.AlterField(
            model_name='product',
            name='openseaLink',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='openseaLink'),
        ),
        migrations.AlterField(
            model_name='product',
            name='raribleLink',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='raribleLink'),
        ),
        migrations.AlterField(
            model_name='product',
            name='solahartLink',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='solahartLink'),
        ),
    ]
