# Generated by Django 3.2 on 2022-04-22 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20220323_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='project_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.projecttype', verbose_name='project_theme'),
        ),
        migrations.AlterField(
            model_name='product',
            name='theme',
            field=models.CharField(max_length=100, null=True, verbose_name='work_theme'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.type', verbose_name='category'),
        ),
    ]
